#FROM nvidia/cuda:11.6.0-cudnn8-devel-ubuntu20.04
FROM nvidia/cudagl:11.3.0-devel-ubuntu20.04

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && apt-get install -y \
	python3-opencv ca-certificates python3-dev git wget sudo ninja-build
RUN ln -sv /usr/bin/python3 /usr/bin/python

RUN wget https://bootstrap.pypa.io/get-pip.py && \
	python3 get-pip.py && \
	rm get-pip.py

RUN pip install tensorboard cmake onnx   # cmake from apt-get is too old
RUN pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 torchaudio==0.12.1 --extra-index-url https://download.pytorch.org/whl/cu113
RUN pip install 'git+https://github.com/facebookresearch/fvcore'

ENV FORCE_CUDA="1"

ARG TORCH_CUDA_ARCH_LIST="Kepler;Kepler+Tesla;Maxwell;Maxwell+Tegra;Pascal;Volta;Turing"
ENV TORCH_CUDA_ARCH_LIST="${TORCH_CUDA_ARCH_LIST}"

RUN pip install 'git+https://github.com/facebookresearch/detectron2'

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
	libjpeg-dev zlib1g-dev \
	libopenexr-dev \
	openexr \
	python3-dev \
	libglfw3-dev libglfw3 \
	libglew-dev \
	libassimp-dev \
	libnuma-dev \
	clang \
	## for bop cpp renderer
	curl \
	autoconf \
	libtool \
	## for uncertainty pnp
	libeigen3-dev \
	libgoogle-glog-dev \
	libsuitesparse-dev \
	libatlas-base-dev \
	## for nvdiffrast/egl
	cmake curl pkg-config \
	libgles2 \
	libgl1-mesa-dev \
	libegl1-mesa-dev \
	libgles2-mesa-dev \
	# (only available for Ubuntu >= 18.04)
	libglvnd0 \
	libgl1 \
	libglx0 \
	libegl1 \
	libglvnd-dev \
	libglew-dev \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt

RUN mkdir gdrnpp_bop2022
WORKDIR /gdrnpp_bop2022

# Install ROS2 dependencies
RUN apt-get update && apt-get install -y \
    curl \
    gnupg2 \
    lsb-release

# Add the ROS2 repository
RUN curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | apt-key add -
RUN sh -c 'echo "deb [arch=amd64,arm64] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" > /etc/apt/sources.list.d/ros2-latest.list'

# Install ROS2 Humble
RUN apt-get update && apt-get install -y \
    ros-galactic-desktop

# bypass issue: TypeError: FormatCode() got an unexpected keyword argument 'verify'
RUN pip install yapf==0.40.1

# for ROS2 development setup (workspace)
RUN apt update
RUN apt install python3-colcon-common-extensions -y
RUN echo "source /usr/share/colcon_argcomplete/hook/colcon-argcomplete.bash" >> ~/.bashrc
RUN mkdir /ros2/ros2_ws/src -p

RUN echo 'export PYTHONPATH="${PYTHONPATH}:/gdrnpp_bop2022"' >> /opt/ros/galactic/setup.bash

# Source the ROS2 setup.bash script
RUN echo "source /opt/ros/galactic/setup.bash" >> /root/.bashrc
RUN echo "source /ros2/ros2_ws/install/setup.bash" >> /root/.bashrc

# for successfull colcon build commands
RUN apt update
RUN apt install python3-pip -y
RUN pip3 install setuptools==58.2.0

WORKDIR /ros2/ros2_ws/src





